### PR TITLE
WorkEffort cron recurrences

### PR DESCRIPTION
**Pull request by ccarlow**

### CODE REVIEW

**Comment by ccarlow** [comment]
David, I resubmitted closed my last pull request after realizing you committed the recurStartCron and recurLimit fields to WorkEffort and changed the logic to use your additions.

Thanks again for the cronExpression suggestion. As you said, its way cleaner and cron-utils already supports all the scheduling logic that would otherwise have to be manually implemented which would be redundant.

I used com.cronutils.model.CronType.QUARTZ for parsing because it supports specifying weekday of a month such as the 2nd Monday of October for Columbus Day (0 15 10 ? 10 2#2).

CronType.UNIX doesn't seem to support day of the month and day of the week together because it applies an OR operation rather than an AND. Therefore the Columbus Day crontab you specified at the end of HolidayUsaData.xml (1 0 8,9,10,11,12,13,14 10 1) would result in scheduling for October 8-14 as well as Mondays. This seems like a bug but members insisted it was by design: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=460070

There is logic to handle spanning multiple days. So if the Columbus Day WorkEffort.allDayEnd is updated 2 days later than the start it will be reflected for ever occurrence.

As far as when the recurStartCron should expire, I changed the recurLimit field to recurEndDate because it seems easier than determining the number of occurences.  E.g. if Columbus Day is removed as a holiday in the future it would be difficult to determine how many times it needs to recur especially since the allDayStart was set to 1937-10-11 (the year the holiday first began).

If these changes are acceptable I'll work on creating crontabs for the other holidays unless you think its a good idea to leave holidays as separate WorkEffort records for each year.

**Comment by jonesde** [comment]
I'll review this more in the near future, next couple days look rough though (surprise visit to a client's customer). I don't know if you saw the code in the ScheduledJobRunner.groovy file but the QUARTZ cron variant is the one I used there as well, definitely has some nice extensions to standard Unix cron.

**Comment by jonesde** [comment]
Just read the rest of your comments on the recurEndDate field you added. If an event should span multiple days per recurrence it might be best to reflect that in the estimatedWorkTime... but this strikes me as a rare scenario. Right now the main pattern used in events is start date/time plus 'work' duration to determine what to show on the calendar (there are a few forms currently in SimpleScreens that only allow entry of estimatedStartDate and estimatedWorkDuration). To support this scenario IMO this is cleaner, and I think more similar to how many modern calendar apps (including Google Calendar) support event setup (along with allowing either an end date or a limit count).

On the other hand maybe this is overloading the *CompletionDate and allDayEnd fields... or maybe not, part of the intent of those fields is you could have something like a task where the completion date is days or weeks after the start date, and there is already the notion of a different between calendar time (estimatedWorkDuration) and the time worked within that duration (estimatedWorkTime).

So yes, I think using the *CompletionDate or allDayEnd fields for the end of a recurrence (if count limit not specified) is fine. On the other hand, maybe we shouldn't have a limit count as that is more difficult to calculate and if a limit count is specified by a user just calculate the end date.

Your thoughts on all this?

**Comment by ccarlow** [comment]
Commit 9dc7baa set the StartEndOut map to null before running the service that sets it because it was maintaining previous endDate values when a workeffort completion dates supporting time were null which was causing unexpected behavior like the tasks spanning more than a day and through the next year.

**Comment by ccarlow** [comment]
David, commit d5795dc isn't related to the work effort cron recurrences like the prior commits and adds boms as consumed products for the create#ProductionRuns service.  

Do you have a preference on how commits/pull requests are submitted (separate branches or grouped together like this)?  Maybe the pull request description just needs to be changed to something less narrow.

**Comment by jonesde** [comment]
Per-feature forks are much easier to manage, likely for both of us as changes may go through multiple revisions before being merged.

BTW, for a quick look this service name doesn't look right: "get#mantle.work.ManufacturingServices.ProductBomDetail"

**Comment by ccarlow** [comment]
Thanks David.  I corrected the service name and a few other things and things tested positive.

I'm going to leave the commit here for now since it is small unless you think I should move it to a separate feature fork which I'll be sure to do from now on.

Also, I'm not sure if you still get notifications on comments added to closed issues but I ran into some problems trying to use your suggested solution for https://github.com/moqui/mantle-udm/issues/57 to which this production run bom commit relates.

**Pull request merged**
