### PR TITLE
Receive and record physicalInventoryId and physicalInventoryCountSeqId.

### PR DESCRIPTION
**Pull request by jenshp**
Record details as per changes in https://github.com/moqui/mantle-udm/pull/26

### CODE REVIEW

**Comment by jonesde** [comment]
Let's wait on changes in mantle-usl until we have the entity model more final in mantle-udm.

**Comment by jenshp** [comment]
Updated to match the changes merged into mantle-udm.

**Comment by jonesde** [comment]
In the record#PhysicalInventoryQuantity service please change the quantityOnHand in-parameter back to 'quantity' as it was before, ie retain backward compatibility (and no good reason I can think of for the change). 

Also for backward compatibility a physicalInventoryCountId should not be required and while you didn't specify it as required in the service def if a valid one is not passed there will be an NPE on the line that sets physicalInventoryCount.quantityOnHand.

Other than those 2 points it looks good, will be a good improvement to these services.

**Comment by jonesde** [comment]
There's an issue in the if.@condition you added (missing 'Id'). I'll merge this and cleanup a couple things, please see the follow up commit that I do and consider it as further feedback.

**Pull request merged**
