### PR TITLE
Add  CommunicationEventContent Services

### PR DESCRIPTION
**Pull request by zhangwei1979**

### CODE REVIEW

**Comment by danieltaylor-nz** [comment]
I checked this out and ran it locally without issue. Would you consider adding some Communication Event Content to the demo data here?

https://github.com/moqui/HiveMind/blob/master/data/HiveMindDemoData.xml

**Comment by danieltaylor-nz** [comment]
I merged this, but unfortunately, I failed to request this change to be made first. So I implemented it myself in the following PR:
https://github.com/moqui/mantle-usl/pull/154

**Comment by zhangwei1979** [comment]
> I checked this out and ran it locally without issue. Would you consider adding some Communication Event Content to the demo data here?
> 
> https://github.com/moqui/HiveMind/blob/master/data/HiveMindDemoData.xml

Yes, but I think it's better we have the uploading event communication content implemented for Add/Edit/Reply Comment on TaskSummary screen

**Comment by danieltaylor-nz** [comment]
Yes, I saw that too. There was no easy way for me to test your PR as there was no demo data with content, and no easy way to add content.

**Comment by zhangwei1979** [comment]
Please check PR https://github.com/moqui/HiveMind/pull/35

**Pull request merged**
